### ISSUE TITLE
little tip

### ISSUE THREAD

**Issue by marcussacana** [Nielk1/NekoPuppet#5]
is it not possible to inject something in the process of the game to read the data with xor?
You can have more compatible games ...
you know, like Xp3viewer always work in Kirikiri games

**Comment by Nielk1** [comment]
I would like to add some more dynamic data loading, but for the moment I've not been able to find a wide enough range of test cases to come up with something more generic.  Additionally, I am trying to write the loaders so they read game files directly to make it easier for end users.

I tried to run 私がお世話してあげる！and ルミナスハーツS on my rooted android VM so I could get at their assets like I did モン娘☆は～れむ (Mont daughter Rem) but they didn't want to download their assets on first-run due to either connectivity issues or my location (I'm in the US and these are Japaneses games).

**Comment by marcussacana** [comment]
No Problem, and exist some files in others game, this resource doesn't is a image? wtf kkk, i have a unexported emote file (.mmo) for sample the emote_logo.mmo don't looks have image, and don't is a string... wtf
[config.zip](https://github.com/Nielk1/NekoPuppet/files/139118/config.zip) (psb)
[emote_logo.zip](https://github.com/Nielk1/NekoPuppet/files/139121/emote_logo.zip) (mdf > psb)
i don't need open this emote_logo, but for me this config have a resouce in same format... :/

**Comment by marcussacana** [comment]
and i make more "c-like" decrypt code...

http://pastebin.com/basgJUgG
`

**Comment by Nielk1** [comment]
I believe we may need to compare the PSB file compressed in an MMO (MDF) with a decrypted PSB from a game.  Something is different that is leading to issues loading the PSB extracted from the MMO.

It might just be a version number in the header field, or a bigger difference such as a section of editor data that needs to be stripped.

**Comment by Animelubitel** [comment]
How do you find out the addresses in the file?

> Example
> 
> using System;
> using System.Collections.Generic;
> using System.IO;
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;
> 
> namespace PSB_Decrypt_Test
> {
> class Program
> {
> static void Main(string[] args)
> {
> if (args.Length < 1) return;
> string Filename = args[0];
> if (!File.Exists(Filename)) return;
> 
> string passKey = "742877301"; // this varries depending on the emotedriver the PSB was made foe
> // you can find it via a string search of the emotedriver's library
> // look for a numeric string above other strings like "source"/"I@source",
> // "texture", "type", "RGBA8", "pixel", "mipMap", etc.
> 
> UInt32 _ecx_0x10_ = 0;
> byte unkIter = 0x0A; // might be string length?
> for (byte itr = 0; itr < passKey.Length; itr++)
> {
> _ecx_0x10_ = _ecx_0x10_ * unkIter + ((uint)passKey[itr] - 0x30);
> }
> 
> //UInt32 _ecx_0x00_ = 0x0F1F38B8;
> UInt32 _ecx_0x04_ = 0x075BCD15; // fixed
> UInt32 _ecx_0x08_ = 0x159A55E5; // fixed
> UInt32 _ecx_0x0C_ = 0x1F123BB5; // fixed
> //UInt32 _ecx_0x10_ = 0x2C476875; // set by dll
> //UInt32 _ecx_0x10_ = 0x0AC111AC; // set by dll
> UInt32 _ecx_0x14_ = 0x00000000; // fixed
> UInt32 _ecx_0x18_ = 0x00000000; // fixed
> 
> UInt32 eax;
> UInt32 esi;
> UInt32 edx;
> 
> using (FileStream fsOut = File.OpenWrite(Filename + @".bin"))
> using (BinaryWriter writer = new BinaryWriter(fsOut))
> {
> using (FileStream fs = File.OpenRead(Filename))
> using (BinaryReader reader = new BinaryReader(fs))
> {
> UInt32 FileMarker = reader.ReadUInt32(); // PSB\0
> writer.Write(FileMarker);
> 
> UInt32 UnkVer = reader.ReadUInt32(); // Perhapse version?
> writer.Write(UnkVer);
> 
> UInt32 DataOff1 = reader.ReadUInt32(); // data offset
> writer.Write(DataOff1);
> 
> UInt32 DataOff2 = reader.ReadUInt32(); // data offset agaim
> writer.Write(DataOff2);
> 
> UInt32 Unknown1 = reader.ReadUInt32(); // unknown
> writer.Write(Unknown1);
> 
> UInt32 Unknown2 = reader.ReadUInt32(); // unknown
> writer.Write(Unknown2);
> 
> UInt32 UnkOff3 = reader.ReadUInt32(); // Unknown Offset 3
> writer.Write(UnkOff3);
> 
> UInt32 UnkOff4 = reader.ReadUInt32(); // Unknown Offset 4
> writer.Write(UnkOff4);
> 
> UInt32 ImageOffset = reader.ReadUInt32(); // ImageDataOffset
> writer.Write(ImageOffset);
> 
> UInt32 Unknown5 = reader.ReadUInt32(); // Unknown
> writer.Write(Unknown5);
> 
> //ASSERT(reader.BaseStream.Position == DataOff1);
> while (reader.BaseStream.Position < UnkOff3)
> {
> if (_ecx_0x14_ == 0x00000000)
> {
> eax = _ecx_0x04_;
> esi = _ecx_0x10_;
> edx = eax;
> edx = edx << 0x0B;
> edx ^= eax;
> eax = _ecx_0x08_;
> _ecx_0x04_ = eax;
> eax = _ecx_0x0C_;
> _ecx_0x08_ = eax;
> eax = esi;
> eax = eax >> 0x0B;
> eax ^= edx;
> eax = eax >> 0x08;
> eax ^= esi;
> eax ^= edx;
> _ecx_0x0C_ = esi;
> _ecx_0x10_ = eax;
> _ecx_0x14_ = eax;
> _ecx_0x18_ = 0x00000004;
> }
> byte dl = (byte)_ecx_0x14_; // truncate, get lowest byte
> byte Data = reader.ReadByte();
> Data ^= dl;
> writer.Write(Data);
> _ecx_0x14_ = _ecx_0x14_ >> 0x08;
> _ecx_0x18_--;
> }
> 
> int len = (int)(reader.BaseStream.Length - reader.BaseStream.Position);
> writer.Write(reader.ReadBytes(len), 0, len);
> }
> }
> }
> }
> }
> 


Or show articles or materials on which you have learned
Do not ignore please
Thank you in advance

**Comment by marcussacana** [comment]
this is the newest algorithm to decrypt
https://github.com/Nielk1/NekoPuppet/blob/master/NekoPuppet/NekoPuppet/MainForm.cs#L936

the 
`string passKey = "742877301"; `
he found manually searching in the game binaries...

**Comment by Animelubitel** [comment]
I mean in the sense of how hacking?

**Comment by Animelubitel** [comment]
> How do you find out the addresses in the file?

Thank you, I meant from where, in the sense of hacking?
I do not need a script
I want to learn, understand myself how to find these addresses and write a script
I need to know the similar data from one file on my own
Sey me how please
Thank you in advance

**Comment by Animelubitel** [comment]
How do you find out the addresses in the file?
Thank you, I meant from where, in the sense of hacking?
I do not need a script
I want to learn, understand myself how to find these addresses and write a script
I need to know the similar data from one file on my own
Sey me how please
Thank you in advance


>Среда, 19 апреля 2017, 1:59 +04:00 от Marcus André <notifications@github.com>:
>
>this is the newest algorithm to decrypt
>https://github.com/Nielk1/NekoPuppet/blob/master/NekoPuppet/NekoPuppet/MainForm.cs#L936
>the
>string passKey = "742877301";
>he found manually searching in the game binaries...
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Аниме Любитель
anime_lubitel@mail.ru
