### ISSUE TITLE
AMV File

### ISSUE THREAD

**Issue by marcussacana** [Nielk1/NekoPuppet#6]
After you can add support to read AMV files? for me is of this "AplhaMovieVideo.dll" plugin...
AYUV? with zlib? i don't know, but i like a way to convert this format probably allow make full unc patchs

**Comment by Nielk1** [comment]
Is this an e-mote file or just another common file from VNs?  I ironically know very little about these files or their usage, despite my progress with PSBs.

**Comment by marcussacana** [comment]
Used for animations in the nekopara, but don't is for e-mote...
but no problem, i make my own stuff
http://www35.zippyshare.com/v/HRjkYLGo/file.html (Decoder/data/video is the decoder location)
