### ISSUE TITLE
Nekopara Vol.2

### ISSUE THREAD

**Issue by marcussacana** [Nielk1/NekoPuppet#7]
Aparentally use same key in the emotedrive.dll
and you know the key of oficial emotedrive sampe game?
The sample game is open source, and if you write a tool to encrypt/decrypt to sample emotedrive... possible allow anyone make custom games with emote...
(i have the academic sdk of emote)

**Comment by Nielk1** [comment]
Added NekoPara Vol.2 support but untested.  Also adjusted loader plugins to not crash when data not present.

Testing of Vol.2 loader needed.  I am re-opening the item till it is confirmed operating properly.

**Comment by marcussacana** [comment]
Hmm I Can test...
anyway i discovery, the Oficial Academic SDK of the E-Mote use this key
'uint MainKey = 192918854; '
and probabbly only this key change... i extract the SDK files and only have this key value... 
(i have the last verision)
![http://i.imgur.com/ZgaI2Yi.jpg](http://i.imgur.com/ZgaI2Yi.jpg)

**Comment by marcussacana** [comment]
the engine works in a simple kirikiri game but with dll and tjs compiled...
the tjs scripts is compiled with this program:
https://github.com/xmoeproject/X-moe/tree/master/ByteCodeAnalysis/tjs2Compiler
If you like decompile is more fast read the source of this compiler to skip debug :v:

**Comment by marcussacana** [comment]
hmm missing dependecies here man, i can't test :/

**Comment by Nielk1** [comment]
Hmm.  What is missing?  I will revise the readme.md with directions to gather dependencies or include them.  It's probably SharpDX: http://sharpdx.org/  NuGet's version was missing things so I downloaded it directly.

I might need to start attaching pre-compiled bins.

**Comment by marcussacana** [comment]
![http://i.imgur.com/l47LRKk.jpg](http://i.imgur.com/l47LRKk.jpg)

**Comment by Nielk1** [comment]
Ah, yes, you need all 3 repos listed in the readme.md as well.  You might need to adjust your references to point to the projects depending on where you put them.

https://github.com/Nielk1/EmoteEngineNet
https://github.com/Nielk1/FunctionalNodeGraphWPF
https://github.com/Nielk1/DotNetZip.ZipReducedKeyDecrypt

**Comment by Nielk1** [comment]
Nekopara Vol.2 Loading is functioning at this time.  It was broken due to an error in the VN specific archive parser.

Additionally, the repository has been changed to use submodules rather than locally pathed dependent working-copies from other repositories.  While this makes the GitHub client throw a fit when attempting to commit to the main repository though all other methods of committing including directly from Visual Studio do function without issue.
